// Single source of truth for the Android Auto Backup rule files.
//
// Pure CommonJS, no dependencies — both withAndroidBackup.js (runs under
// plain Node during `expo prebuild`) and tests/androidBackup.test.js import
// these constants. The config plugin writes them verbatim into the gitignored
// android/ prebuild output every prebuild, so the no-<include> invariant
// below can never silently regress to Expo's default template.
//
// INVARIANT: neither document declares an <include> element. Any <include>
// flips Android into allow-list backup mode, which would silently drop the
// AsyncStorage SQLite DB ("RKStorage") if its filename/location changes
// across react-native-async-storage versions or the new architecture. With
// no <include>/<exclude>, Android backs up all eligible app data by default,
// which always covers the progress store. tests/androidBackup.test.js
// enforces this.

// Legacy Auto Backup rules for Android 11 and below (API <= 30).
const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Legacy Auto Backup rules for Android 11 and below (API <= 30).
  Android 12+ uses data_extraction_rules.xml instead.

  Intentionally empty (no <include>/<exclude>): an empty full-backup-content
  means "back up all eligible app data by default", which includes the
  AsyncStorage SQLite DB ("RKStorage") regardless of its exact filename.
  Declaring an <include> here would flip Android to allow-list mode and risk
  excluding the progress store on async-storage/new-arch changes.

  Generated by plugins/withAndroidBackup.js — do not hand-edit the copy
  under android/ (it is regenerated on every prebuild).
-->
<full-backup-content />
`;

// Android 12+ (API 31+) backup + device-transfer rules.
const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Android 12+ (API 31+) backup rules. Controls Auto Backup to the user's
  Google Drive (via Google Play services) and device-to-device transfer.

  IMPORTANT: no <include> elements are declared on purpose. Adding any
  <include> switches Android into allow-list mode, which would silently
  drop the AsyncStorage SQLite DB ("RKStorage") if its filename/location
  changes across react-native-async-storage versions or the new arch.
  With no include/exclude, Android backs up all eligible app data
  (databases/, shared_prefs/, files/ — excluding cache/ and no_backup/),
  which always covers the progress store.

  This backup is optional from the user's side: it only happens when the
  user is signed into a Google account with "Back up to Google Drive"
  enabled in Android Settings. ~25 MB per-app cap; no API keys required.

  Generated by plugins/withAndroidBackup.js — do not hand-edit the copy
  under android/ (it is regenerated on every prebuild).
-->
<data-extraction-rules>
    <cloud-backup />
    <device-transfer />
</data-extraction-rules>
`;

module.exports = { BACKUP_RULES_XML, DATA_EXTRACTION_RULES_XML };
