// Monochrome system. Every theme is a neutral grayscale (R=G=B, no hue) so the
// whole app reads as a modern black-and-white editorial surface. Magnitude is
// carried by brightness elsewhere; here themes vary only by paper value, so the
// picker still does something without ever introducing colour.
export const THEMES = {
  wado: {
    bg: '#0C0C0C',
    bg2: '#161616',
    panel: '#1C1C1C',
    accent: '#ECECEC',
    accent2: '#FAFAFA',
    particle: '#E0E0E0',
    wash: '#2A2A2A',
    pattern: 'seigaiha',
    name: 'Wado · 和道',
    desc: 'Paper white on charcoal',
  },
  sandai: {
    bg: '#0A0A0A',
    bg2: '#141414',
    panel: '#1A1A1A',
    accent: '#F4F4F4',
    accent2: '#FAFAFA',
    particle: '#EAEAEA',
    wash: '#2C2C2C',
    pattern: 'kaen',
    name: 'Sandai · 鬼徹',
    desc: 'High-contrast ink',
  },
  shusui: {
    bg: '#0E0E0E',
    bg2: '#181818',
    panel: '#1E1E1E',
    accent: '#DCDCDC',
    accent2: '#F2F2F2',
    particle: '#D2D2D2',
    wash: '#282828',
    pattern: 'kumo',
    name: 'Shusui · 秋水',
    desc: 'Soft graphite',
  },
  hollow: {
    bg: '#080808',
    bg2: '#121212',
    panel: '#181818',
    accent: '#E4E4E4',
    accent2: '#F4F4F4',
    particle: '#DADADA',
    wash: '#262626',
    pattern: 'kasumi',
    name: 'Hollow · 虚',
    desc: 'Deep matte black',
  },
  solar: {
    bg: '#101010',
    bg2: '#1C1C1C',
    panel: '#222222',
    accent: '#FAFAFA',
    accent2: '#FCFCFC',
    particle: '#F0F0F0',
    wash: '#303030',
    pattern: 'asahi',
    name: 'Solar · 陽',
    desc: 'Brightest chalk',
  },
  abyss: {
    bg: '#060606',
    bg2: '#101010',
    panel: '#161616',
    accent: '#DADADA',
    accent2: '#EEEEEE',
    particle: '#CFCFCF',
    wash: '#242424',
    pattern: 'uzumaki',
    name: 'Abyss · 深淵',
    desc: 'Near-black obsidian',
  },
  marimo: {
    bg: '#0B0B0B',
    bg2: '#151515',
    panel: '#1B1B1B',
    accent: '#E0E0E0',
    accent2: '#F2F2F2',
    particle: '#D6D6D6',
    wash: '#2A2A2A',
    pattern: 'uzumaki',
    name: 'Marimo · 藻頭',
    desc: 'Neutral slate',
  },
};

export const THEME_KEYS = Object.keys(THEMES);
export const DEFAULT_THEME = 'sandai';
